# Generated by Django 3.1.3 on 2020-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201124_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
