# Generated by Django 3.1.3 on 2020-11-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201124_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateCreated',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
